### ISSUE TITLE
Indexing SVs based on Chr and pos of the breakpoints

### ISSUE THREAD

**Issue by andurill** [rhshah/iCallSV#27]
lines 260-270
` indexList = annoDF.loc[annoDF['chr1'].isin([chrom1]) &
                               annoDF['pos1'].isin([int(start1)]) &
                               annoDF['chr2'].isin([chrom2]) &
                               annoDF['pos2'].isin([int(start2)])].index.tolist()
if(len(indexList) > 1):
            if(verbose):
                logger.fatal(
                    "iCallSV::MergeFinalFile: More then one sv have same coordinate in same sample for annotated file. Please check and rerun")
            sys.exit(1)
        else:
            annoIndex = indexList[0]`

This is an issue for rare reciprocal SVs in which both breakpoint coordinates are identical.

**Comment by rhshah** [comment]
@andurill i am trying to understand this and i still dont get this error because, if they are reciprocal events then shouldn't the the Chromosome 1 become Chromosome 2 for the reciprocal event ?

**Comment by andurill** [comment]
No, for the reciprocal events, the chromosomes (and genes) for the breakpoints 1 and 2 remain the same for both events. Only the fusion description changes based on the read orientation. Check the ALK fusion in this sample for example: {cvr}/sample/10701

**Comment by rhshah** [comment]
Alright so will now think of ways of modifying this. 
![bitmoji](https://render.bitstrips.com/v2/cpanel/8398500-168707425_1-s4-v1.png?transparent=1&palette=1&width=246)

**Comment by rhshah** [comment]
Done
