### ISSUE TITLE
task 1 failed - "'unlist' is not an exported object from 'namespace:Biostrings'"

### ISSUE THREAD

**Issue by haoziyeung** [rhshah/iCallSV#42]
Hello,@rhshah,sorry for bother you again,when i run iCallSV,i met a error like below:

command:
R --slave --vanilla --args 5 /gpfs/users/yanghao/project/shi-jian-zhi-ping/t_n_20171030/illumina /gpfs/users/yanghao/test/iCallSV/StructuralVariantAnalysis/DellyDir/Illumina-B1701-sm/Illumina-B1701-sm_allSVFiltered_tsvInput.txt hg19 150 /gpfs/users/yanghao/test/iCallSV/StructuralVariantAnalysis/DellyDir/Illumina-B1701-sm Illumina-B1701-sm_allSVFiltered_cScore.txt < /gpfs/users/yanghao/software/iCallSV/iCallSV/R/Rscripts/calculateConfidenceScore.R

stdout/stderr:
[1] "mismatch limit increased to 136 to capture reads on both references"
[1] "mismatch limit increased to 137 to capture reads on both references"
[1] "Working on event 20 of 24"
[1] "mismatch limit increased to 138 to capture reads on both references"
[1] "mismatch limit increased to 139 to capture reads on both references"
[1] "mismatch limit increased to 140 to capture reads on both references"
[1] "mismatch limit increased to 141 to capture reads on both references"
[1] "mismatch limit increased to 142 to capture reads on both references"
[1] "mismatch limit increased to 143 to capture reads on both references"
[1] "mismatch limit increased to 144 to capture reads on both references"
[1] "mismatch limit increased to 7 to capture reads on both references"
[1] "mismatch limit increased to 145 to capture reads on both references"
[1] "mismatch limit increased to 8 to capture reads on both references"
[1] "mismatch limit increased to 146 to capture reads on both references"
[1] "mismatch limit increased to 9 to capture reads on both references"
[1] "mismatch limit increased to 147 to capture reads on both references"
[1] "mismatch limit increased to 10 to capture reads on both references"
[1] "mismatch limit increased to 148 to capture reads on both references"
[1] "mismatch limit increased to 11 to capture reads on both references"
[1] "mismatch limit increased to 149 to capture reads on both references"
[1] "mismatch limit increased to 150 to capture reads on both references"
[1] "mismatch limit increased to 151 to capture reads on both references"
[1] "Working on event 22 of 24"
[1] "Working on event 16 of 24"
[1] "mismatch limit increased to 7 to capture reads on both references"
[1] "mismatch limit increased to 8 to capture reads on both references"
[1] "mismatch limit increased to 9 to capture reads on both references"
[1] "mismatch limit increased to 10 to capture reads on both references"
[1] "Working on event 24 of 24"
[1] "mismatch limit increased to 7 to capture reads on both references"
[1] "mismatch limit increased to 8 to capture reads on both references"
[1] "mismatch limit increased to 9 to capture reads on both references"
[1] "Working on event 21 of 24"
**Error in { :
  task 1 failed - "'unlist' is not an exported object from 'namespace:Biostrings'"
Calls: calculateConfidenceScore ... ViewAndScoreFull -> alignViewFull -> %dopar% -> <Anonymous>
Execution halted**

can you help me ?

**Comment by haoziyeung** [comment]
Traceback (most recent call last):
  File "iCallSV.py", line 380, in <module>
    main()
  File "iCallSV.py", line 350, in main
    args.verbose)
  File "/gpfs/users/yanghao/software/iCallSV/iCallSV/mergeFinalFiles.py", line 235, in run
    caseCalls = record.genotype(caseIDinVcf)
  File "/gpfs/users/yanghao/software/anaconda2/lib/python2.7/site-packages/vcf/model.py", line 277, in genotype
    return self.samples[self._sample_indexes[name]]
KeyError: None

**Comment by rhshah** [comment]
Are you trying to run scripts individually?  Also are the two errors that you mentioned are related to the same run. 

The Calculate Confidence Score feature is not validated and doesn't work in all cases, I tried to take advantage of [targetSeqView](https://github.com/Eitan177/targetSeqView) to do this but it does not run successfully in all scenarios, thus I use the value '0' in cases it fails.

**Comment by haoziyeung** [comment]
can i remove targetSeqView,and run all the pipeline of iCallSV?

**Comment by rhshah** [comment]
No you cannot. iCallSV should be able to continue even if targetSeqView fails.

**Comment by haoziyeung** [comment]
First,i run iCallSV, 

python iCallSV.py -sc configuration/template.ini -abam /gpfs/users/yanghao/project/shi-jian-zhi-ping/t_n_20171030/illumina/Illumina-B1701.bam -bbam /gpfs/users/yanghao/project/shi-jian-zhi-ping/t_n_20171030/illumina/Illumina-B17NC.bam -aId Illumina-B1701-sm -bId Illumina-B17NC-sm -o /gpfs/users/yanghao/test/iCallSV -op prefix_for_the_output_files -v

it occurs error:
![1](https://user-images.githubusercontent.com/16606564/35158968-b8de6b84-fd73-11e7-99ef-e4a4aaaf0ed3.png)

i realize maybe it's because targetSeqView,so i run R individually

**Comment by rhshah** [comment]
Thanks for the detailed explanation. Would you mind pasting the `header` of the Illumina-B17NC-sm_allSVFiltered.vcf. The issue most likely looks like is the ID of the samples in the VCF and ID of the samples provided by you on the command line. If they are not the same then you can fix this by making the readgroup in BAM file as same ID as what you are using in command line using AddOrReplaceReadGroups and then rerun. This happens because delly uses readgroup from BAM to assign sample ID.

**Comment by haoziyeung** [comment]
sorry for reply you so slow,here is my header in Illumina-B1701-sm_allSVFiltered.vcf:
##fileformat=VCFv4.2
##fileDate=20180118
##reference=/gpfs/users/yanghao/database/ref/b37/human_g1k_v37_decoy.fasta
##bcftools_viewVersion=1.3.1-16-g16414e6+htslib-1.3.1-31-gf58922d
##bcftools_viewCommand=view -O v -o /gpfs/users/yanghao/test/iCallSV/StructuralVariantAnalysis/DellyDir/Illumina-B1701-sm/Illumina-B1701-sm_dup.vcf /gpfs/users/yanghao/test/iCallSV/StructuralVariantAnalysis/DellyDir/Illumina-B1701-sm/Illumina-B1701-sm_dup.bcf
##INFO=<ID=CIEND,Number=2,Type=Integer,Description="PE confidence interval around END">
##INFO=<ID=CIPOS,Number=2,Type=Integer,Description="PE confidence interval around POS">
##INFO=<ID=CHR2,Number=1,Type=String,Description="Chromosome for END coordinate in case of a translocation">
##INFO=<ID=END,Number=1,Type=Integer,Description="End position of the structural variant">
##INFO=<ID=PE,Number=1,Type=Integer,Description="Paired-end support of the structural variant">
##INFO=<ID=MAPQ,Number=1,Type=Integer,Description="Median mapping quality of paired-ends">
##INFO=<ID=SR,Number=1,Type=Integer,Description="Split-read support">
##INFO=<ID=SRQ,Number=1,Type=Float,Description="Split-read consensus alignment quality">
##INFO=<ID=CONSENSUS,Number=1,Type=String,Description="Split-read consensus sequence">
##INFO=<ID=CE,Number=1,Type=Float,Description="Consensus sequence entropy">
##INFO=<ID=CT,Number=1,Type=String,Description="Paired-end signature induced connection type">
##INFO=<ID=IMPRECISE,Number=0,Type=Flag,Description="Imprecise structural variation">
##INFO=<ID=PRECISE,Number=0,Type=Flag,Description="Precise structural variation">
##INFO=<ID=SVTYPE,Number=1,Type=String,Description="Type of structural variant">
##INFO=<ID=SVMETHOD,Number=1,Type=String,Description="Type of approach used to detect SV">
##INFO=<ID=INSLEN,Number=1,Type=Integer,Description="Predicted length of the insertion">
##INFO=<ID=HOMLEN,Number=1,Type=Integer,Description="Predicted microhomology length using a max. edit distance of 2">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=GL,Number=G,Type=Float,Description="Log10-scaled genotype likelihoods for RR,RA,AA genotypes">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=FT,Number=1,Type=String,Description="Per-sample genotype filter">
##FORMAT=<ID=RC,Number=1,Type=Integer,Description="Raw high-quality read counts for the SV">
##FORMAT=<ID=RCL,Number=1,Type=Integer,Description="Raw high-quality read counts for the left control region">
##FORMAT=<ID=RCR,Number=1,Type=Integer,Description="Raw high-quality read counts for the right control region">
##FORMAT=<ID=CN,Number=1,Type=Integer,Description="Read-depth based copy-number estimate for autosomal sites">
##FORMAT=<ID=DR,Number=1,Type=Integer,Description="# high-quality reference pairs">
##FORMAT=<ID=DV,Number=1,Type=Integer,Description="# high-quality variant pairs">
##FORMAT=<ID=RR,Number=1,Type=Integer,Description="# high-quality reference junction reads">
##FORMAT=<ID=RV,Number=1,Type=Integer,Description="# high-quality variant junction reads">
##FILTER=<ID=PASS,Description="All filters passed">
##FILTER=<ID=LowQual,Description="PE/SR support below 3 or mapping quality below 20.">
##ALT=<ID=DEL,Description="Deletion">
##ALT=<ID=DUP,Description="Duplication">
##ALT=<ID=INV,Description="Inversion">
##ALT=<ID=TRA,Description="Translocation">
##ALT=<ID=INS,Description="Insertion">
##contig=<ID=1,length=249250621>
##contig=<ID=2,length=243199373>
##contig=<ID=3,length=198022430>
##contig=<ID=4,length=191154276>
##contig=<ID=5,length=180915260>
##contig=<ID=6,length=171115067>
##contig=<ID=7,length=159138663>
##contig=<ID=8,length=146364022>
##contig=<ID=9,length=141213431>
##contig=<ID=10,length=135534747>
##contig=<ID=11,length=135006516>
##contig=<ID=12,length=133851895>
##contig=<ID=13,length=115169878>
##contig=<ID=14,length=107349540>
##contig=<ID=15,length=102531392>
##contig=<ID=16,length=90354753>
##contig=<ID=17,length=81195210>
##contig=<ID=18,length=78077248>
##contig=<ID=19,length=59128983>
##contig=<ID=20,length=63025520>
##contig=<ID=21,length=48129895>
##contig=<ID=22,length=51304566>
##contig=<ID=X,length=155270560>
##contig=<ID=Y,length=59373566>
##contig=<ID=MT,length=16569>
##contig=<ID=GL000207.1,length=4262>
##contig=<ID=GL000226.1,length=15008>
##contig=<ID=GL000229.1,length=19913>
##contig=<ID=GL000231.1,length=27386>
##contig=<ID=GL000210.1,length=27682>
##contig=<ID=GL000239.1,length=33824>
##contig=<ID=GL000235.1,length=34474>
##contig=<ID=GL000201.1,length=36148>
##contig=<ID=GL000247.1,length=36422>
##contig=<ID=GL000245.1,length=36651>
##contig=<ID=GL000197.1,length=37175>
##contig=<ID=GL000203.1,length=37498>
##contig=<ID=GL000246.1,length=38154>
##contig=<ID=GL000249.1,length=38502>
##contig=<ID=GL000196.1,length=38914>
##contig=<ID=GL000248.1,length=39786>
##contig=<ID=GL000244.1,length=39929>
##contig=<ID=GL000238.1,length=39939>
##contig=<ID=GL000202.1,length=40103>
##contig=<ID=GL000234.1,length=40531>
##contig=<ID=GL000232.1,length=40652>
##contig=<ID=GL000206.1,length=41001>
##contig=<ID=GL000240.1,length=41933>
##contig=<ID=GL000236.1,length=41934>
##contig=<ID=GL000241.1,length=42152>
##contig=<ID=GL000243.1,length=43341>
##contig=<ID=GL000242.1,length=43523>
##contig=<ID=GL000230.1,length=43691>
##contig=<ID=GL000237.1,length=45867>
##contig=<ID=GL000233.1,length=45941>
##contig=<ID=GL000204.1,length=81310>
##contig=<ID=GL000198.1,length=90085>
##contig=<ID=GL000208.1,length=92689>
##contig=<ID=GL000191.1,length=106433>
##contig=<ID=GL000227.1,length=128374>
##contig=<ID=GL000228.1,length=129120>
##contig=<ID=GL000214.1,length=137718>
##contig=<ID=GL000221.1,length=155397>
##contig=<ID=GL000209.1,length=159169>
##contig=<ID=GL000218.1,length=161147>
##contig=<ID=GL000220.1,length=161802>
##contig=<ID=GL000213.1,length=164239>
##contig=<ID=GL000211.1,length=166566>
##contig=<ID=GL000199.1,length=169874>
##contig=<ID=GL000217.1,length=172149>
##contig=<ID=GL000216.1,length=172294>
##contig=<ID=GL000215.1,length=172545>
##contig=<ID=GL000205.1,length=174588>
##contig=<ID=GL000219.1,length=179198>
##contig=<ID=GL000224.1,length=179693>
##contig=<ID=GL000223.1,length=180455>
##contig=<ID=GL000195.1,length=182896>
##contig=<ID=GL000212.1,length=186858>
##contig=<ID=GL000222.1,length=186861>
##contig=<ID=GL000200.1,length=187035>
##contig=<ID=GL000193.1,length=189789>
##contig=<ID=GL000194.1,length=191469>
##contig=<ID=GL000225.1,length=211173>
##contig=<ID=GL000192.1,length=547496>
##contig=<ID=NC_007605,length=171823>
##contig=<ID=hs37d5,length=35477943>
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  Illumina_B1701-sm       Illumina_B17NC-sm

**Comment by rhshah** [comment]
Than you for pasting the header of vcf as you can see from the header the
Sample ID has `_` after Illumina in the sample ID and what you have provided to the script does not as you can see below:
`-aId Illumina-B1701-sm -bId Illumina-B17NC-sm`

Can you please try running it with the:
`-aId Illumina_B1701-sm -bId Illumina_B17NC-sm`

Do let me know if you see any issue further.

**Comment by haoziyeung** [comment]
thanks a lot,i'll try again with the right sample ID

**Comment by haoziyeung** [comment]
Hi,@rhshah,it's all right now ,thank you ,it's a great software.

**Comment by rhshah** [comment]
I am glad it worked and it is useful.
